spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
server:
  port: 8080
security:
  jwt:
    secret-key: yt3Jm2UOMfoAi21Ho1Pae3ncS2gh3Qaj55iAf3oOEvm39A2j87eGa
    expiration-time: 3600000
